sudo: false
language: python
python:
  - "2.7"
  #- "3.5"
env:
 - secure: "Nhlp2gUpbLWQacM60vT803Ph298V5JxTIl115xQK6aCRxNPgd5n1ZT9Arjk3nLWnCzESnHaq/zihmLfazB77K9HXdsjoj0wvg6J08/BjqYmGdBlNaV8ESlK2odLmPInq+FFlGvN+BOzaNnHoV0pcjTdMg0zWmtt2odpmA+dyVrDpeM2bg5qO64l/1gieZuXn3N/Qgcg5xYTPESCBVS4nji7S8W0OkXXwuBcCop+vDFpbvvelLwRVjhkEXxt/QCtDHN+0k4EyqRdDq9bL4qqfH+huCXdtYr5PQMlph3R09vlS0MG+DklbesLPvYUMbY+vS35mIUjNmqA13PuzITZeGp01j13YWGS/7QvX1tKLhE+Jlds0BUWoAGym8yZnEWlGCT+2UAh6UP9Jxxe3Ez0CE4aMuk+rKf+pu5tvy9LRkNT4NAikNQMAEe3E8t61B60eHZeDnaDpWWgjRjDuJpoWlI4Zvy9oT7ovaANXFMySz4tW7sgxO7zYpsRH5fo6/AavHKHfhpIiDhR1K+N5MHaIBss6aG9FSMxtuNQQOAkdQjpz+wmG4qm+pGem7hLMyx9nzt1bIGe960W82EGNn0IczOBZ3wtU76cXy3RTtm9IzT/nm/29PqoN7aKUM8J43AWj9HWLM3mJRiPBjRE0YcM8EjWawETlYcUFhIqroL+ERwc="
 - secure: "FQcjJah5GKbQTcGvUtZyLJT29MGAfc57tin4U/Wr7s8L9JF/WEG47TKvxx1iibgYSkat6AqjXQGah82lGOAGVpfGntKeRpNOOsac8exbqHpRVjqZmgHACWbeqGxk25hj9ckQQgILOwrIYViFSzEIfDoFgWIUCkidYyAFY3sEVrH2rYmQ48aTBFPgFml8qtNSGanZMskEd8uABobF5mEwGKyKrWddtv6VICJrFIjhrPg3gk2zJX1pzOvRYtlQ0p+t0zUxGoJLPmc4bFOe0qndZP7a4OjdHUHucKu9YHHJjvCV+wbLR1R7/MHCibDS7V4vdanRQH+Yh8oWctHAUfkyQRNRR8PZaMdGud1wWJDqxKeWBbIL0TTWb0k0HRub8X2rNqq8BhLNaAqiqpDWZVkyeT+W/lVc1BKRFZLMEztwkrlLVeSNc5nfznnLtbuzu9yeJXCKA5OxL4xDIRtSIU8CfJSwNY90ktSK9eyelh6H6oPQrwq4G+at3v0JRiZ/gpMPf10RF5fzjq2oixl8+nz//AzA/amYUuBwE7DWwKpRmi2JMp1i+W1a5bFiNqCIXnU3bP2axZdPI/ODNfObEq6agCYD4qtG35M0WzBcQYxFzvbD0kquKg2XBPKx7hyr0wmoF8BHrbV4hc9Nzf3sryTcEq6E6OJ51X9nU2PdWkfqFpA="
 - caas_credentials.apiurl: https://api-ap.dimensiondata.com
 - caas_credentials.datacenter: EU6 
before_install:
 - pip install paramiko PyYAML jinja2 httplib2 passlib nose mock
 - git clone git://github.com/ansible/ansible.git --recursive /home/travis/build/ansible
 - source /home/travis/build/ansible/hacking/env-setup
script:
  - pwd
  - ls
  - ls /home/travis
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  #- python3.5 -m compileall -fq .
  - ansible-playbook test/01-setup.yml