sudo: false
language: python
python:
  - "2.7"
  #- "3.5"
env:
  global: 
    - secure: "VGWWZxqOsBnTKdTq2iRE/E7+5DpJDW3+i/C/MUhyAEcTepeo6W4p6VcY5NJkd2tOiZaMyTDlpBYqQXdIiNyHmGL+EqFH8ynm+AaCdACpgoEVGPykr1BHR8OM73rNU9RvIeW/YdhtvM2AL8RBbnINYLxW1psAfmB/VZ/L4v1DYibXtpGacyp66MThlNPCq1Z7bZ7/wXFKJuA6jSsu+BqMlHRiICxQmBE5CZ2PfyAn3/V0PIU8csWhPLgPhdCsTNFNg2ZWAW3JJuG/l+co6o/LYsVw+rHLxPWoZCABDZnzC/JnF1zOgeKhBf+94qQCc3LW8d5SDV558Q1HAH+Zrn896PdqiEA35xrFLNLZRE5GjUlb+7FZ+vWAt0a2vdCeEAmlJ6LhxqBIviU2D5pCV0/01P3exNBvypkCH6G7j2wQjvpeVgAbXuSjnsrJhFhYRCqXPQocSaCvcUadiiUkEfNXj11mIBCfxghS+0pRfUW+vdK+q70XiF8/OVHGIQZ5+7mJNqnih7OK0knwESvdFbt42b6RFHfGXRWXn9aWhGexwXoSt2oI0C4bbNOCGh5cSmuykBt24Qtpp5wIk8NJ/XZ67lM4VWwEe1ApfHbxcYIqGwD4rnvjTiiYUgZks1Sag/77f+r9q5qsRMMxlnoqEclgeNUfVfd4JpCwMCJ+u46x0Qc="
    - secure: "upwJ9DLqKphm8yDxbLHTVk85JV6wdY8Sbmr8qbzCzhtofzJmLNFGXRgQsHdm0Yx4G7dEKH+MQ6BLQjP49IR0+1Cr+nV1qRx4KClB/dtaUvpdthY1GDkDGxz4wwXBDYEgwGb2OWUpYnFEQTjrXN/hWiGxFCw7sdWUJA+umYFZR3lPZCP3Dp1YWNG/St7CkX2u9u21VMmYX0qtP9mcJD6brAaIp/aSd7Y35pRCCLh3KQvZuuQHEi3HPqhNho2VRuRUdcMTpgya9tTCGKqxJXg5vVqdIbFT41IhXQbFalmEAiLIBtSg7gnhBUXjq+jsk+o87aa1talCy1jXdrU1WJd6u9TKRAlgOXvLIJXiEwXizk7aIv9SxXWpNGs6kAkEcy5k+SZGXrnhBwKAArbjSvNa1cVJ8UxVaso/WJTuEMSTfHrjK4mPavfFomOpHJv2gR7dE6uEPcAIMGr9T0PJzlCgx4oxb4xFSBhUNZIzHgRLYbojOEmOBX985b18H1sz8Flw5H9JSo7xCEkRbPNpIewujpn32WGfmdjqbp2Q8gwY4CD7O1CslUCWJbPO+y5jyjrp4EL6Vic2FT19hS1MN5HCfp9K0oQaatDVjfh4FO5cOIlsPnFst7qsjidEExRn80IwlY2ICWeluI/BDk4hs319KH72VWqW4mMcaRt/zQ+pEtI="
    - caas_credentials.apiurl=https://api-eu.dimensiondata.com
    - caas_credentials.datacenter=EU6 
before_install:
 - pip install paramiko PyYAML jinja2 httplib2 passlib nose mock
 - git clone git://github.com/ansible/ansible.git --recursive /home/travis/build/ansible
 - source /home/travis/build/ansible/hacking/env-setup
 - ln -s library /home/travis/build/ansible/lib/ansible/modules/extras/cloud/dimension_data
script:
  - ls /home/travis/build/ansible/lib/ansible/modules/extras/cloud/dimension_data
  - pwd
  - ls
  - ls /home/travis
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  #- python3.5 -m compileall -fq .
  - ansible-playbook test/01-setup.yml