sudo: false
language: python
python:
  - "2.7"
  #- "3.5"
env:
  global: 
    - secure: "VGWWZxqOsBnTKdTq2iRE/E7+5DpJDW3+i/C/MUhyAEcTepeo6W4p6VcY5NJkd2tOiZaMyTDlpBYqQXdIiNyHmGL+EqFH8ynm+AaCdACpgoEVGPykr1BHR8OM73rNU9RvIeW/YdhtvM2AL8RBbnINYLxW1psAfmB/VZ/L4v1DYibXtpGacyp66MThlNPCq1Z7bZ7/wXFKJuA6jSsu+BqMlHRiICxQmBE5CZ2PfyAn3/V0PIU8csWhPLgPhdCsTNFNg2ZWAW3JJuG/l+co6o/LYsVw+rHLxPWoZCABDZnzC/JnF1zOgeKhBf+94qQCc3LW8d5SDV558Q1HAH+Zrn896PdqiEA35xrFLNLZRE5GjUlb+7FZ+vWAt0a2vdCeEAmlJ6LhxqBIviU2D5pCV0/01P3exNBvypkCH6G7j2wQjvpeVgAbXuSjnsrJhFhYRCqXPQocSaCvcUadiiUkEfNXj11mIBCfxghS+0pRfUW+vdK+q70XiF8/OVHGIQZ5+7mJNqnih7OK0knwESvdFbt42b6RFHfGXRWXn9aWhGexwXoSt2oI0C4bbNOCGh5cSmuykBt24Qtpp5wIk8NJ/XZ67lM4VWwEe1ApfHbxcYIqGwD4rnvjTiiYUgZks1Sag/77f+r9q5qsRMMxlnoqEclgeNUfVfd4JpCwMCJ+u46x0Qc="
    - secure: "gKsvEu8XS+oLsBk246RW8xPWoae+VZ4ih6oyBd2R2AcZ5rHR6V7dWQKNi0/qurL/PlTLDFrYCBFU6gQV9gABm5UmWfP2uKoEhTmxu4+wdVsc9PL2+o1+9TvVfHe9ynNV4manKq52qYF3fDFX/47w0VWsrsRJzOLbmM93qXu2twLrShvgCYi5Id/p1vvUx5VfXIy/w2t0E47/VvB8jMNMy3VKNJf6mB0ZuzyY2KIq9st5VhvF/C/e192eYEobIJmEpMfJpBJZWyEEfcWaYZjK7kpo/hqw0Zbqztl25NumOisARhPzCLFxTNsdfjYEd42yrZoTI5HDmSSrZa3sWEzWJdey7Qae0YCX6nEm4Z5U3oQA/7CcVyHzs042jLXkVAz+IMszs8uSL5TPRFAm7crVkZc10OaZaDcvjxQ2wHjX2Q121UWuyVEXHBa5qa3qRrxitZhIzcwRZwltKCifhetPaBBxP6mUuVMgLPPp8fgx6HjbJ9tZ1Z6f72JcH9V7wFuyJw9I/5cVstr/x89GdXuUgverIjxMIj+aMPVjH/QrE1cN6CTqR4g+2iJZGk+O6kzl4mmPVu3o6mZkBYsqvgVTh7lHvNBQUyrZLWsBLl+gevXb56bwYsMtxbGuGvZ3j0pkp+uE3KZTW+Ddk4mmIP3C2KuAwI9EmgCjS5XmpMacIpM="
    - caas_credentials.apiurl=https://api-eu.dimensiondata.com
    - caas_credentials.datacenter=EU6 
before_install:
 - pip install paramiko PyYAML jinja2 httplib2 passlib nose mock
 - git clone git://github.com/ansible/ansible.git --recursive /home/travis/build/ansible
 - source /home/travis/build/ansible/hacking/env-setup
script:
  - pwd
  - ls
  - ls /home/travis
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  #- python3.5 -m compileall -fq .
  - ansible-playbook test/01-setup.yml